n001=4123456795 # Kein Export: MUSS in ARCHIV-BESTAND/PHASE-2 als 4123456795.xml existieren. DARF KEINE REF-XML haben.
n002=4123456796 # Kein Export: MUSS in ARCHIV-BESTAND/PHASE-2 als 4123456796.xml existieren. DARF KEINE REF-XML haben.
