# CREFO::[{Used-By-Customer;...}],[IKA-AUFTR-CLZ],[{BTLG-CREFO;...}],[BEFR|BILANZ|BEIDES],[ABLEHNUNG_FIRMA_FIRMA|ABLEHNUNG_FIRMA_PRIVPERSON|...],[CTA_STATISTIK],[DSGVO_SPERRE]
# Version:: 2
1234567890::[C01;C02],[],[1234567892],[KEINE],[KEINE],[],[]
1234567891::[C01;C02],[],[],[KEINE],[KEINE],[],[]
1234567892::[],[],[],[KEINE],[KEINE],[],[]
4123456790::[C05],[],[1234567892],[KEINE],[KEINE],[],[]
