p001=1234567892 # Diese Testcrefo MUSS im Verzeichnis ARCHIV-BESTAND/PHASE-2 als 1234567892.xml existieren, MUSS auch EINE entsprechende REF-XML Datei p001_1234567892.xml im Verzeichnis REF-EXPORTS/PHASE-2/c01/Relevanz_Negativ haben!
x002=1234567891 # Löschsatz-X-Fall: MUSS in ARCHIV-BESTAND/PHASE-2 als 1234567891.xml existieren. REF-XML optional.

