# CREFO::[{Used-By-Customer;...}],[IKA-AUFTR-CLZ],[{BTLG-CREFO;...}],[BEFR|BILANZ|BEIDES],[ABLEHNUNG_FIRMA_FIRMA|ABLEHNUNG_FIRMA_PRIVPERSON|...],[CTA_STATISTIK],[DSGVO_SPERRE]
# Version:: 2
1234567890::[C01;C02;C03;C04],[],[],[KEINE],[KEINE],[],[]
1234567891::[C01;C02;C03;C04],[],[],[KEINE],[KEINE],[],[]
1234567892::[C01;C04],[],[],[KEINE],[KEINE],[],[]
1234567893::[C02;C04],[],[],[KEINE],[KEINE],[],[]
1234567894::[C04],[],[],[KEINE],[KEINE],[],[]
1234567895::[C04],[],[],[KEINE],[KEINE],[],[]
